resource_types:
- name: ckr
  type: docker-image
  source: 
    repository: jmkarthik/ckr5
    tag: latest

resources:
- name: my-ckr
  type: ckr
  source:
    token: token1

jobs:
- name: my-ckr-job
  plan:
  - get: my-ckr
  - put: my-ckr